NHSDigital/communications-manager-api

azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, proxies/sandbox/apiproxy/policies/AssignMessage.MessageBatches.Create.Request.xml, proxies/sandbox/apiproxy/policies/AssignMessage.MessageBatches.Create.Response.xml, proxies/sandbox/apiproxy/policies/ExtractVariables.MessageBatches.Create.Response.xml, proxies/sandbox/apiproxy/policies/JavaScript.MessageBatches.Create.Request.xml, proxies/sandbox/apiproxy/policies/RaiseFault.400BackendException.DuplicateRequestItemRefIds.xml, proxies/sandbox/apiproxy/policies/RaiseFault.400BackendException.MissingDataArray.xml, proxies/sandbox/apiproxy/policies/RaiseFault.400BackendException.MissingRequestRefId.xml, proxies/sandbox/apiproxy/policies/RaiseFault.400BackendException.MissingSendingGroupId.xml, proxies/sandbox/apiproxy/policies/RaiseFault.404InvalidRoutingPlan.xml, proxies/sandbox/apiproxy/policies/RaiseFault.404NotFound.xml, proxies/sandbox/apiproxy/resources/jsc/MessageBatches.Create.Request.js, proxies/sandbox/apiproxy/targets/sandbox.xml
CCM-814, CCM-816, CCM-815
Adds proxying of POST /v1/message-batches to POST /api/v1/send on the
backend.
Adds support for handling of these exceptions thrown by the backend
service:
* 400 - Duplicate requestItemRefIds
* 400 - Missing data array
* 400 - Missing requestRefId
* 400 - missing sendingGroupId
* 404 - Invalid routing plan
* 404 - Generic error
=> CCM-814, CCM-816, CCM-815

specification/communications-manager.yaml
Adds a link to https://digital.nhs.uk/services/nhs-number for information when reference NHS Number in existing spec. Only 1 x ref to NHS number found.
=> CCM-987- adds link to NHS Number info in existing spec 

tests/development/create_message_batches/test_success.py, tests/sandbox/create_message_batches/test_success.py
If we wanted a more secure RNG library for this we could replace `random` with `secrets`, but honestly the usage of randomness here is just to generate a 10 digit string of numbers for the mocked NHS number - there's absolutely no point in someone predicting this random value when literally any 10 digit string will work as a valid NHS number for the sandbox backend.
The main question is - do we even need the randomness in this test? We could just as easily use a hard-coded 10 digit string.
In this PR I've replaced the randomness with a fixed string.
=> CCM-1254: Removed randomness from tests

proxies/shared/policies/AssignMessage.AuthenticationDetails.xml
Removes the X-Client-Id header from downstream requests.
This cannot be accepted and deployed until https://nhsd-git.digital.nhs.uk/riskstrat/communications-manager/-/merge_requests/377 has been promoted into the mainline.
=> CCM-1290 - remove x-client-id

specification/communications-manager.yaml, tests/development/content_types/test_406_errors.py, tests/integration/content_types/test_406_errors.py, tests/lib/constants.py, tests/sandbox/content_types/test_406_errors.py
Corrects the 406 response content type so it is set to application/vnd.api+json.
The reason why it is this, and not application/json is that our API outputs application/vnd.api+json by default.
On an unacceptable Accept header we must always respond with the default.
Adds an assertion on the 406 tests to ensure the default header is returned in the response.
=> CCM-1604 - 406 documented response content type

Makefile, docs/proxies.md, docs/tests/sandbox/index.md, docs/tests/sandbox/post_v1_message-batches/index.md, docs/tests/sandbox/post_v1_message-batches/service_ban.md, proxies/shared/partials/Partial.Flows.CreateMessageBatchEndpoint.xml, proxies/shared/partials/Partial.Flows.RateLimiting.xml, proxies/shared/partials/Partial.Target.FaultRules.xml, proxies/shared/partials/Partial.Target.PreFlowRequest.xml, proxies/shared/policies/RaiseFault.403ServiceBan.xml, sandbox/app.spec.js, sandbox/handlers.js, specification/communications-manager.yaml, specification/schemas/ForbiddenResponse.yaml, specification/schemas/enums/EnumErrorForbidden.yaml, tests/docs/sandbox/post_v1_message-batches/index.rst, tests/docs/sandbox/post_v1_message-batches/service_ban.rst, tests/lib/constants.py, tests/lib/generators.py, tests/sandbox/authentication/test_401_errors.py, tests/sandbox/authentication/test_403_errors.py, tests/sandbox/create_message_batches/test_service_ban.py
Adds a new policy that allows for service ban responses from the backend solution to trigger a custom 403 response within the API proxy.
Ensures that the sandbox mock application can throw errors in the same way as the backend application, with test coverage over it and the policy being run.
Updates the documentation for the proxy to include the new logic around the handling of 403 & 403 service bans.
Adds the 403 service ban information to the API specification.
=> CCM-1616 - Service bans

proxies/shared/policies/AssignMessage.MessageBatches.Create.Request.xml
Adds the value `MessageBatch` into the idempotency key header value sent to /api/v1/send on the backend service.
This is to ensure there is no collision between the new /api/v1/messages idempotency keys and the /api/v1/send idempotency keys.
=> CCM-1611 message batch idempotency key

poetry.lock, pyproject.toml
Bumped pytest-nhsd-apim to 3.3.9 & remove pyjwt
=> CCM-2399: Bump pytest-nhsd-apim to 3.3.9 & remove pyjwt

proxies/shared/resources/jsc/SetResponseDefaults.js, tests/development/headers/test_x_amz_removal.py, tests/integration/headers/test_cors.py, tests/integration/headers/test_x_amz_removal.py, tests/lib/assertions.py, tests/lib/constants/constants.py, tests/production/headers/test_cors.py, tests/production/headers/test_x_amz_removal.py, tests/sandbox/headers/test_cors.py, tests/sandbox/headers/test_x_amz_removal.py
This work aims to remove amazon headers from the response, Ive taken a regex approach to pattern match on x-amz. I have extended the testing assertion library to assert on 3 different types on headers which also covers the majority of edge cases e.g. casing and amzn type headers.
=> CCM-2152: Remove aws headers from responses

package.json, specification/communications-manager.yaml, specification/documentation/APIDescription.md, specification/documentation/CreateMessage.md, specification/documentation/CreateMessageBatch.md, specification/responses/4xx/message_batches/404_NoSuchRoutingPlanForBatch.yaml, specification/responses/4xx/messages/404_NoSuchRoutingPlanForMessage.yaml
Updated content in OAS spec to rename Communications Manager to NHS Notify. Haven't changed the spec file name or touched any other naming changes - just user-visible content.
=> CCM-2970 AMP-2407 rename comms mgr api to nhs notify

scripts/calculate_version.py
Fix calculate_version.py for patch version
=> CCM-3210: fix calculate_version.py for calculating patch versions

proxies/shared/partials/Partial.Target.FaultRules.xml, proxies/shared/resources/jsc/MessageBatches.Create.Request.js, sandbox/__test__/batch_send.spec.js, sandbox/__test__/messages.spec.js, sandbox/handlers/batch_send.js, sandbox/handlers/messages.js, tests/lib/assertions.py
This passes requests for message batches straight through to the backend now rather than converting their formatting and passing them through in the format of the old API.
This PR makes a number of changes to demonstrate that this version of the code works in tandem with the code I am proposing to merge currently deployed to my own dynamic environment. To achieve this some changes are temporary and will need to be reverted before squashing the PR. These are the changes to:
```
proxies/live/apiproxy/targets/target.xml
proxies/shared/policies/AssignMessage.MessageBatches.Create.Request.xml
proxies/shared/policies/AssignMessage.Messages.Create.Request.xml
proxies/shared/policies/AssignMessage.Messages.GetSingle.Request.xml
```
=> CCM-1924: convert message batches API to pass-through

tests/development/messages/get_message/test_success.py, tests/integration/messages/get_message/test_success.py, tests/lib/assertions.py, tests/production/messages/get_message/test_success.py, tests/sandbox/messages/get_message/test_success.py
The assert_200_response_message function checks various properties of the response returned by APIM. One such property is the url of links. In Prod it was incorrectly checking that it begins with prod.api.service.nhs.uk, when it's actually api.service.nhs.uk.
The test passing in 6 of the 7 environments has been confirmed locally(see below). Currently unable to test `prod-sandbox-test` locally, but will try and resolve that before merging.
=> CCM-3517: amend assert_200_response_message to handle prod url

RELEASING.md
To avoid dropping branch protection during a release, the process has been amended to include a new `release branch` that will be merged into the `release` branch.
=> CCM-3335: update release steps

scripts/perform-static-analysis.sh
Current sonar scans are failing due to an outdated image. Using latest version resolves this.
=> Update sonar docker image

sandbox/package-lock.json, sandbox/package.json
Removes two vulnerabilities introduced by express and one of it's dependencies, qs.
=> CCM-3718: update express to beta 3

sandbox/package-lock.json, sandbox/package.json
Updates supertest to v7.0.0 to remove vulnerability in v6.3.4's peer dependency (formidable v2.1.2)
Build pipeline successfully ran showing sandbox test suite that uses `supertest` is functioning as expected.
=> CCM-4853: update supertest to 7.0.0

.gitignore, azure/nightly-zap-scan-pipeline.yml, docs/proxies.md, proxies/live/apiproxy/targets/target.xml, proxies/sandbox/apiproxy/targets/sandbox.xml, proxies/shared/partials/Partial.Target.PreFlowRequest.xml, proxies/shared/partials/Partial.Target.PreFlowResponse.xml, scripts/publish_zap_compatible.py, scripts/run_zap.sh, zap/zap.yaml
Actioning the ZAP issues so the workflow runs green.
Successful security scan: https://dev.azure.com/NHSD-APIM/API%20Platform/_build/results?buildId=211413&view=results
We do not want the responses to be cached, and set the headers to indicate this.
Sec-Fetch-* headers are only for requests. This rule is not relevant for APIs on their own.
The KSUIDs are sometimes being detected as base64 strings.
In our error responses we include a link to the NHS developer catalogue.
The ZAP code is picking up `developer`.
When there is no Origin header in the request, we do not include the CORS headers in the response. This includes the Cross-Origin-Resource-Policy, which is what ZAP is flagging.
In our error responses we include the apigee message id in the body.
Sometimes it can be detected as a …
=> CCM-4566 fix zap vulnerabilities

specification/schemas/enums/ErrorInvalidValue.yaml, specification/schemas/responses/errors/message_batches/UnableToProcessBatch.yaml, specification/schemas/responses/errors/messages/UnableToProcessMessage.yaml, specification/schemas/types/LinksErrorNHSNumber.yaml
Added NHSnumber link info to status 400 info in:
https://digital.nhs.uk/developer/api-catalogue/nhs-notify#post-/v1/message-batches
https://digital.nhs.uk/developer/api-catalogue/nhs-notify#post-/v1/messages
=> CCM-2615: added NHS Number link to docs in spec

specification/documentation/APIDescription.md
CCM-5300: updated roadmap url in APIDescription to use NHS Notify as tag instead of comms manager 
This directs the user to the correct page when clicked
=> CCM-5300: updated roadmap url in APIDescription to use NHS Notify as tag instead of comms manager

.github/pull_request_template.md
CCM-5423: removed dyn env deploy check item from MR template
=> CCM-5423: removed dyn env deploy check item from MR template

specification/communications-manager.yaml, specification/endpoints/get_nhsapp_account_details.yaml, specification/snippets/ODSOrganisationCodeParameter.yaml, specification/snippets/PageNumberParameter.yaml
This adds the documentation for the query string parameters to somewhere bloomreach will render it. We reproduced the problem documented in bloomreach and confirmed that this solution showed the documentation as updated. The documentation text is exactly what was already approved.
=> CCM 5695 missing querystring params

specification/callbacks/channel-subscription-openapi-spec.json, specification/schemas/components/SupplierStatus.yaml
Trivial update to the documentation for channel status callbacks: `messageStatusDescription` -> `channelStatusDescription`
=> CCM-5798: Update channel status callback doc

azure/nightly-zap-scan-pipeline.yml, scripts/publish_zap_compatible.py, scripts/run_zap.sh, specification/schemas/components/SupplierStatus.yaml, specification/schemas/enums/MessageStatusEnum.yaml, specification/schemas/enums/SupplierStatusEnum.yaml, specification/schemas/responses/MessageResponse.yaml, zap/Dockerfile
Updates to the Zap scan:
- Update bash script to exit on a failure. The zap scan is run inside a docker container and if it failed then the script would go on and the pipeline would still show as green.
- Update the openapi specs used by zap in order to exclude the callback URLs defined in the documentation. The 4 endpoints scanned are now: Get Message, Post Message, Post Batch and Get NHS App Accounts.
- Update the definition of the SupplierStatus and ChannelStatus enums to have a unique file name. This was causing a warning followed by an automatic appending of the suffix "-2"
- Use the previous version of zap: 2.14.0. The current version 2.15.0 is causing some errors that I believe are from the jython script `zap/scripts/authentication/get_bearer_token.js` but I couldn't get to the …
=> CCM-5754: Fail zap pipeline when error in bash

specification/callbacks/message_status.yaml
remove duplication of sending status in message status callbacks doc
=> CCM-6000: remove duplication of sending status in message status callbacks doc

tests/lib/authentication.py
Changes auth logic in E2E to retrieve new token if current token is about to expire in 15 seconds.
Token has a validity of 3 minutes.
=> CCM-6020: generate new token if current will expire in 15s

proxies/shared/partials/Partial.Target.FaultRules.xml, proxies/shared/policies/ExtractVariables.ErrorDetails.xml, proxies/shared/policies/ExtractVariables.ErrorMessage.xml, proxies/shared/policies/JavaScript.EnhanceErrorDetails.xml, proxies/shared/policies/RaiseFault.GenericErrorDetails.xml, proxies/shared/resources/jsc/EnhanceErrorDetails.js, sandbox/__test__/messages.spec.js, sandbox/handlers/config.js, sandbox/handlers/messages.js, sandbox/handlers/utils.js
This change is to handle an array of errors returned by the backend. Each error item contains:
- A title
- A pointer to the field causing the error
- A message
The implementation has been kept generic for now (no hardcoded status codes or reason phrases) in the hope that it can be reused in the future.
Note that automated tests are supposed to be added as part of [CCM-5328](https://nhsd-jira.digital.nhs.uk/browse/CCM-5328).
=> CCM-5025: Contact details override error responses

docs/tests/development/post_v1_message-batches/validation.md, sandbox/__test__/batch_send.spec.js, sandbox/handlers/batch_send.js, tests/development/message_batches/create_message_batches/test_field_validation.py, tests/sandbox/message_batches/create_message_batches/test_field_validation.py
Front-end update to accommodate the backend now returning a messageIndex for batch contact details validation errors.
Note that https://github.com/NHSDigital/comms-mgr/pull/184 needs to be merged and deployed to internal-dev first.
Tests run against de-sila7:
=> CCM-6415: Return message index for contact details APIM tests

specification/callbacks/channel_status.yaml, specification/callbacks/message_status.yaml, specification/responses/4xx/callbacks/429_TooManyRequests_Callbacks.yaml
Added details of 429 response code to both Message and Channel status callbacks
=> CCM-6618: Added details of 429 response code to callback docs

azure/azure-release-pipeline.yml, manifest_template.yml, proxies/live/apiproxy/targets/target.xml
Create a new proxy pointing a the ref2 backend. The base URL to access will be `https://ref.api.service.nhs.uk/comms-2`
Deployed using this pipeline: https://dev.azure.com/NHSD-APIM/API%20Platform/_build/results?buildId=247788&view=logs&j=78ebf54a-ef06-5d5d-de23-54348247b70e&t=bc6420b1-fc92-5c3c-6e37-ffa2864a4d70
Note that the failing tests are caused by the fact that Ref2 does not contain CCM-6415 which should be released as part of 4.27.0.
=> CCM-6534 Introduce ref2

tests/lib/helper.py
Adds a default timeout for all browser actions in the NHS app message check test function.
=> CCM-6362: add default timeout for NHS app test function

tests/lib/helper.py
Add a global timeout for expect functions 
* [] Dev
=> CCM-6362: add global timeout for expect functions

sandbox/__test__/batch_send.spec.js, sandbox/__test__/messages.spec.js, sandbox/handlers/batch_send.js, sandbox/handlers/config.js, sandbox/handlers/error_scenarios/global_free_text.js, sandbox/handlers/messages.js, sandbox/handlers/utils.js
- Added global free text SMS and Email routing configs to sandbox
- Updated error message that was returned when NHS App free text personalisation field was missing to align with the error returned in the BE
- Before: `Expect single personalisation field of 'body'`
-  After: `Some personalisation fields are missing: body` 
- Updated logic so that if unrecognised personalisation parameter is provided but required parameters have also been provided, sandbox returns 200/201 instead of 400. This aligns with validation in the BE
=> CCM-6453: add freetext sms and email to sandbox

docs/tests/sandbox/post_v1_message-batches/validation.md, docs/tests/sandbox/post_v1_messages/validation.md, sandbox/__test__/batch_send.spec.js, sandbox/__test__/messages.spec.js, sandbox/handlers/error_scenarios/override_contact_details.js, tests/docs/partials/validation/test_not_permitted_to_use_contact_details.rst, tests/lib/constants/constants.py, tests/sandbox/message_batches/create_message_batches/test_field_validation.py, tests/sandbox/messages/create_messages/test_field_validation.py
This PR is change the error response when a client tries to use the override contact details, when they do no have feature enable. 
Old response
```
{    
"message": "Client is not allowed to provide alternative contact details"
} 
```
new response client response after Apigee: 
```
{
"errors": [
{
"id": "rrt-8127824057098449875-a-geu2-9147-6573781-2.0",
"code": "CM_CANNOT_SET_CONTACT_DETAILS",
"links": {
"about": "https://digital.nhs.uk/developer/api-catalogue/communications-manager"
},
"status": "400",
"title": "Cannot set contact details",
"detail": "Client is not allowed to provide alternative contact details.",
"source": {
"pointer": "/data/attributes/recipient/contactDetails"
}
}
]
}
```
* [] Dev
=> CCM-6595: Transform override contact details error response to match our API

Makefile, tests/lib/assertions.py, tests/lib/authentication.py, tests/lib/constants/constants.py, tests/lib/error_handler.py, tests/lib/fixtures.py, tests/sandbox/test_500_errors.py
Edit: Unfortunately we still got 401 errors after implementing the solution below because we can get 100s of successful tests before getting random failures. I think we can still keep this solution but I also added retries for individual tests.
It can take up to 5 minutes for Apigee to register that a Product has been added to an Application. This can sometimes cause APIM tests to fail because of 401 errors (and tests that are expecting 401s to be false positives).
Some logic has been added to the token generation for tests in order to test the token multiple times to make sure the authentication is working before proceeding to the tests. If the authentication is not ready (the test request returns a 401) then the logic waits 10 seconds before trying again.
One would think the correct …
=> CCM-6648: Fix intermittent 401 errors

specification/documentation/CreateMessage.md, specification/documentation/CreateMessageBatch.md
Removing references to deduplicating requests from single message and batch message endpoints ahead of possible breaking change
=> CCM-7379: remove references to deduplicating requests in api docs

tests/integration/messages/create_messages/test_field_validation.py
Fixes broken import in test file which is causing e2e to fail on int - blocking promotion of the release to prod
Following the [APIM patching steps](https://nhsd-confluence.digital.nhs.uk/display/RIS/Patching+Steps)
=> CCM-6416: fix broken import in e2e

manifest_template.yml
Update ref and ref2 to allow up to 1800 transactions per second.
- Quota: set to 1800 * 60 = 108000 transactions per minute
- Rate limit: also set to 108000 to allow for 1800 TPS. The unit of this parameter is TPM but it's applied to seconds, see https://nhsd-confluence.digital.nhs.uk/display/APM/Rate+limiting+shared+flow for more info.
=> CCM-7019: Set rate limit to 1800 TPS for ref and ref2

Makefile, azure/periodic-mtls-dev-pipeline.yml, azure/periodic-mtls-prod-pipeline.yml, azure/templates/teams-alert.yml, tests/mtls/test_mtls.py
The changes made in this PR:
- Create two new pipeline jobs that run on a 10 minute schedule for the dev environments (internal-dev, internal-qa) and prod environments (int, prod)
- Update the tests to assert that a general exception is raised, rather than a specific exception (connection reset by peer) and rename them to reflect updated functionality
- Altered the alerting message to remove references to the frequency they are ran, all existing tests will now report: "Environment Test Failure, Environment tests have failed, investigate and review..."
- After this PR has been merged the existing job can be deleted
New pipelines created for mTLS Dev and mTLS prod
[mTLS Dev ](https://dev.azure.com/NHSD-APIM/API%20Platform/_build?definitionId=691) failure alert
[mTLS Prod …
=> CCM-7948: Break out mTLS pipeline to dev and prod, update tests to assert generic exception

tests/development/messages/create_messages/test_not_permitted_to_use_contact_details.py, tests/development/rate_limiting/test_429_errors.py
This PR resolves the intermittent test failure on internal-dev for the test 'test_not_permitted_to_use_contact_details'. The intermittent failure was caused by two tests attempting to set a rate limit value on the same client at the same time.
Removing the correlation-id aspect of the test ensures that only one test is ran using NHS Notify Client ID during the standard internal-dev test run so we can continue to run the whole test suite with 4 parallel runners without significantly compromising on the value of what is being tested.
=> CCM-8114: Remove parametrisation from tests using NHS Notify Test Client

docs/tests/development/post_v1_message-batches/happy_path.md, docs/tests/development/post_v1_messages/happy_path.md, proxies/shared/resources/jsc/helpers/validationChecks.js, sandbox/__test__/batch_send.spec.js, sandbox/__test__/messages.spec.js, sandbox/handlers/error_scenarios/override_contact_details.js, specification/responses/4xx/message_batches/400_UnableToProcessMessageBatch.yaml, specification/responses/4xx/messages/400_UnableToProcessMessage.yaml, tests/development/message_batches/create_message_batches/test_field_validation.py, tests/development/message_batches/create_message_batches/test_success.py, tests/development/messages/create_messages/test_field_validation.py, tests/development/messages/create_messages/test_success.py, tests/docs/partials/happy_path/test_201_message_batch_undefined_nhs_number.rst, tests/docs/partials/happy_path/test_201_messages_undefined_nhs_number.rst, tests/integration/message_batches/create_message_batches/test_field_validation.py, tests/integration/messages/create_messages/test_field_validation.py, tests/lib/constants/message_batches_paths.py, tests/lib/constants/messages_paths.py, tests/production/message_batches/create_message_batches/test_field_validation.py, tests/production/messages/create_messages/test_field_validation.py, tests/sandbox/message_batches/create_message_batches/test_field_validation.py, tests/sandbox/messages/create_messages/test_field_validation.py
Amend NHS number validation so that if the NHS number is undefined it returns true for anonymous patients feature.
Note: as part of this work, the AWS APIM integration test client was changed to add "allowAnonymousPatient":true
=> CCM-8384: Amend NHS number validation

tests/development/message_batches/create_message_batches/test_success.py, tests/development/messages/create_messages/test_success.py, tests/integration/message_batches/create_message_batches/test_success.py, tests/integration/messages/create_messages/test_success.py, tests/lib/constants/constants.py, tests/sandbox/message_batches/create_message_batches/test_success.py, tests/sandbox/messages/create_messages/test_success.py
This PR adds tests to verify that sms contact detail override accepts international numbers.
=> CCM-8891: Add allow international sms numbers tests

specification/callbacks/channel_status.yaml, specification/callbacks/message_status.yaml, specification/documentation/APIDescription.md
Also fixed a relative link under Free-Text Comms
and removed the" Message status" and "Supplier status" sections completely (as the content is now hosted on the external content site)
=> CCM-8596: Update Message and Channel Status Callback docs

proxies/shared/partials/Partial.Target.FaultRules.xml, proxies/shared/resources/jsc/EnhanceErrorDetails.js, sandbox/__test__/batch_send.spec.js, sandbox/__test__/messages.spec.js, sandbox/handlers/error_scenarios/override_contact_details.js
This is a minor change to accommodate this BE PR: https://github.com/NHSDigital/comms-mgr/pull/515 in order to:
- Use the status code returned by the BE for each error item
- Not populate the source on an error item when it's not provided by the BE
- Allow the BE to return 404 errors and translate them instead of just returning a generic error
Note that the internal-dev tests can only pass with the new BE.
=> CCM-8270: Aggregate error items

specification/documentation/APIDescription.md
Updates to the "Free text communications" section of the public API documentation. Details of expected changes [here](https://nhsd-confluence.digital.nhs.uk/spaces/RIS/pages/1018848799/1.4+Enable+users+to+write+and+send+messages+from+your+software)
=> CCM-9523: Update API docs for free-text comms

specification/documentation/APIDescription.md, specification/schemas/components/Recipient.yaml
Updated the public API documentation to add name fields to Contact Details Override (schema and example payloads) on the send single and send batch endpoints
Removed the "Required" indicator from the `nhsNumber` field and added a note that it is normally mandatory unless agreed with onboarding team.
Also fixed a broken link in the Overview section.
=> CCM-8392: [API Docs] Add name override fields to msg send endpoints

README.md, example.env, sandbox/__test__/batch_send.spec.js, sandbox/__test__/messages.spec.js, sandbox/handlers/error_scenarios/override_contact_details.js, specification/documentation/APIDescription.md, specification/schemas/components/Recipient.yaml, tests/end_to_end/test_email.py, tests/end_to_end/test_letter.py, tests/end_to_end/test_nhsapp.py, tests/end_to_end/test_sms.py, tests/lib/helper.py
=> CCM-9458 Release 4.41.0

specification/schemas/components/MessageStatus.yaml
Override `channelStatus` enum values when used in MessageStatus callback
When used in the MessageStatus callback, the `channelStatus` is populated from the summary information on the RequestItem so will only ever have values for the terminal states: `delivered | failed`. Currently the documentation states that it could also show the intermediate states.
When used on the ChannelStatus callback or the GetStatus endpoint, the payload is populated from the detailed information on the RequestItemPlan so should continue to show the intermediate states.
=> CCM-9861: [API docs] Override `channelStatus` enum values

specification/schemas/components/Recipient.yaml
Update API Docs to detail international phone number support for SMS contact override
=> CCM-9521: SMS Api Docs for international support

.github/dependabot.yml, package.json, pnpm-lock.yaml, sandbox/package.json, sandbox/pnpm-lock.yaml
I've run pnpm update -r to update the files to see if this will fix the dependabot issue. However, it looks to have updated possibly more then we originally wanted. I've put this PR here to see what others think before attempting to merge it and see if it clears.
=> CCM-10553: Fix Dependabot Redoc 
