NHSDigital/communications-manager-api

azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, manifest_template.yml, specification/communications-manager.yaml
=> CMM-845 Enable sandbox

azure/project.yml
=> CMM-845: Updated proxy base path

sandbox/app.js, sandbox/app.spec.js, sandbox/handlers.js, sandbox/package-lock.json, sandbox/package.json
Adds mock response for POST /api/v1/send, including the same validation as the current backend service (at the time of authoring).
Checks include:
* missing request body
* missing sendingGroupId
* missing requestRefId
* missing data array
* missing requestItemRefId within data array
* duplicate requestItemRefId values within data array
* sendingGroupId validation against the following list: ** b838b13c-f98c-4def-93f0-515d4e4f4ee1
** 49e43b98-70cb-47a9-a55e-fe70c9a6f77c
** b402cd20-b62a-4357-8e02-2952959531c8
** 936e9d45-15de-4a95-bb36-ae163c33ae53
** 9ba00d23-cd6f-4aca-8688-00abc85a7980
Includes the ability to simulate a 500 error, which can be thrown by the existing backend when there is an error writing to the dynamodb table. This is done by sending a requestRefId value of simulate-500. …
=> CCM-814, CCM-816

proxies/live/apiproxy/policies/JavaScript.MessageBatches.Create.Validate.xml, proxies/live/apiproxy/policies/RaiseFault.400BadRequest.xml, proxies/live/apiproxy/proxies/default.xml, proxies/live/apiproxy/resources/jsc/MessageBatches.Create.Validate.js, proxies/live/apiproxy/targets/target.xml, proxies/sandbox/apiproxy/policies/JavaScript.MessageBatches.Create.Validate.xml, proxies/sandbox/apiproxy/policies/RaiseFault.400BadRequest.xml, proxies/sandbox/apiproxy/resources/jsc/MessageBatches.Create.Validate.js, proxies/sandbox/apiproxy/targets/sandbox.xml, tests/test_400_errors.py
=> CMM-817: Added raisefault for 400 error

specification/communications-manager.yaml
=> CMM-825: Removed 431 header too large error from spec as this is handled by Apigee.

manifest_template.yml, proxies/sandbox/apiproxy/policies/FlowCallout.ApplyRateLimiting.xml, proxies/sandbox/apiproxy/proxies/default.xml
=> CMM-824: Enabled shared rate limiting flow

Makefile, azure/azure-release-pipeline.yml
Uses the sandbox prod tests for testing sandbox.
=> CCM-937 - Sandbox tests

specification/communications-manager.yaml
Updated the description key to include multi-line values
=> Spec headers

tests/test_too_many_requests.py
=> CCM-824: Tests

tests/test_field_validation.py
=> CCM-817: Field validation tests

tests/test_not_found.py
=> CCM-816: 404 valid uri invalid request type

proxies/live/apiproxy/policies/JavaScript.SetResponseContentType.xml, proxies/live/apiproxy/proxies/default.xml, proxies/live/apiproxy/resources/jsc/SetResponseContentType.js, proxies/live/apiproxy/targets/target.xml, tests/test_content_type_harmony.py
Adds content-type negotiation for both responses and errors.
Cannot be included in master until CCM-923 is merged.
=> CCM-931 content negotiation

proxies/live/apiproxy/resources/jsc/MessageBatches.Create.Validate.js, proxies/sandbox/apiproxy/resources/jsc/MessageBatches.Create.Validate.js, tests/test_field_validation.py, tests/test_too_many_requests.py
tests will break until CCM-983 is resolved
=> CCM-983: Tests

tests/test_unauthorized.py
=> CCM-924: Add invalid auth prod tests

azure/azure-release-pipeline.yml
Fixes type in azure release pipeline.
=> Fixes type in azure release pipeline.

specification/communications-manager.yaml
Updates documentation inline with feedback received.
=> Docs updates

azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, proxies/live/apiproxy/targets/target.xml
=> CMM-918: Added secret ids for TLS-MA certs

azure/templates/run-tests.yml
=> CCM-845: Updated apigee ID to use sandbox value from SM

proxies/live/apiproxy/policies/RaiseFault.406NotAcceptable.xml, proxies/live/apiproxy/targets/target.xml, tests/test_not_acceptable.py
=> CCM-928: Add 406 prod tests

proxies/live/apiproxy/policies/RaiseFault.415UnsupportedMedia.xml, proxies/live/apiproxy/targets/target.xml, tests/test_unsupported_media.py
=> CCM-927: Add 415 Prod tests

specification/communications-manager.yaml
=> CCM-975 Response type title amend to sentence case

specification/communications-manager.yaml
Added in contact details for other queries as per feedback from API-M review.
=> CCM-975 API status and roadmap

specification/communications-manager.yaml
removed extra '/' at end of sandbox URL as per feedback
=> CCM-975 sandbox url amend

specification/communications-manager.yaml
=> CCM-975 error section added inline with feedback

tests/test_400_errors.py, tests/test_forbidden.py, tests/test_no_such_routing_plan.py, tests/test_not_acceptable.py, tests/test_not_found.py, tests/test_timeouts.py, tests/test_too_many_requests.py, tests/test_unauthorized.py, tests/test_unsupported_media.py, tests/test_x_correlation_id.py
=> CCM-930: Add x-correlation-id prod tests

specification/communications-manager.yaml
Removed anchor links and surrounding text to enable publication.
=> Removes onboarding anchor links and surrounding text

specification/communications-manager.yaml
=> This removes text and links referencing Comms Manager Service Page

manifest_template.yml, proxies/live/apiproxy/policies/RaiseFault.429TooManyRequests.xml, proxies/live/apiproxy/targets/target.xml, proxies/sandbox/apiproxy/targets/sandbox.xml, sandbox/app.spec.js, sandbox/handlers.js, tests/test_no_such_routing_plan.py
=> CCM-920: No such routing plan test

proxies/live/apiproxy/policies/JavaScript.500DuplicateTemplates.ExtractDuplicates.xml, proxies/live/apiproxy/policies/RaiseFault.500DuplicateTemplates.xml, proxies/live/apiproxy/policies/RaiseFault.500MissingTemplates.xml, proxies/live/apiproxy/resources/jsc/500DuplicateTemplates.ExtractDuplicates.js, proxies/live/apiproxy/targets/target.xml, proxies/sandbox/apiproxy/policies/JavaScript.500DuplicateTemplates.ExtractDuplicates.xml, proxies/sandbox/apiproxy/policies/RaiseFault.500DuplicateTemplates.xml, proxies/sandbox/apiproxy/policies/RaiseFault.500MissingTemplates.xml, proxies/sandbox/apiproxy/resources/jsc/500DuplicateTemplates.ExtractDuplicates.js, proxies/sandbox/apiproxy/targets/sandbox.xml, sandbox/app.spec.js, sandbox/handlers.js, specification/communications-manager.yaml, tests/lib/constants.py, tests/lib/generators.py, tests/sandbox/create_message_batches/test_invalid_routing_plan.py
Adds 500 errors for missing or duplicate templates.
=> CCM-1065, CCM-1066

specification/communications-manager.yaml
Amends spec inline with feedback on descriptions / non tech elements (see https://nhsd-jira.digital.nhs.uk/browse/CCM-1119)
=> Part amend of Spec inline with Tony's feedback

specification/communications-manager.yaml
As per request from API-M review
=> Amends 'Create message batch' to 'Send messages'

tests/sandbox/create_message_batches/test_invalid_routing_plan.py
=> CCM-1064: Tests

proxies/live/apiproxy/policies/RaiseFault.500FailedWriteToDynamoDB.xml, proxies/live/apiproxy/targets/target.xml, proxies/sandbox/apiproxy/policies/RaiseFault.500FailedWriteToDynamoDB.xml, proxies/sandbox/apiproxy/targets/sandbox.xml, sandbox/app.spec.js, sandbox/handlers.js, specification/communications-manager.yaml
=> CCM-1082: 500 DynamoDB Exception Handling

README.md, postman/CommunicationsManager.postman_collection.json, postman/Development.postman_environment.json, postman/Integration.postman_environment.json, postman/Sandbox.postman_environment.json
=> CCM-1149: Update postman collection to generate authentication

scripts/calculate_version.py
=> Release 3.2

manifest_template.yml, specification/communications-manager.yaml
=> Release 3.2.0

azure/templates/run-tests.yml
=> CCM-967: Added proxy check before test runs

proxies/shared/partials/Partial.Target.FaultRules.xml
=> CCM-1216 - 500 exceptions

.github/workflows/pr-lint.yaml
Updated the bot regex to search for CCM prefixed strings
=> CCM-1089: PR Bot Fix

sandbox/app.js
=> CCM-1255: Removed `x-powered-by` header from express

scripts/process_imports.py
=> CCM-1251: Enabled auto-escaping on jinja2 environment

sandbox/Dockerfile
=> CCM-1253: Added nonroot user to dockerfile

package-lock.json, package.json, proxies/shared/resources/jsc/MessageBatches.Create.Validate.js, proxies/utils/performance/Performance_MessageBatches.Create.Validate.js, tests/sandbox/create_message_batches/test_field_validation.py
Adds script that allows for performance testing of create message validation scenarios.
Increases the performance on the validation script.
=> CCM-1228 - validation performance

tests/test_endpoints.py
=> CCM-1230: Added security negative test for missing status apikey

Makefile, poetry.lock, pyproject.toml, tests/lib/assertions.py
=> CCM-1128: Handle unexpected 429 response

Makefile, azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, azure/nightly-int-dev-pipeline.yml, azure/templates/run-tests.yml, tests/integration/content-types/test_406_errors.py, tests/integration/content-types/test_415_errors.py, tests/integration/content-types/test_content_type_negotiation.py, tests/integration/create_message_batches/test_field_validation.py, tests/integration/headers/test_cors.py, tests/integration/headers/test_x_correlation_id.py, tests/integration/test_404_errors.py, tests/lib/__init__.py, tests/lib/authentication.py
CCM-1169: Add int auth tests
CCM-1169: Add int auth tests
=> CCM-1169: Add int auth tests

.github/dependabot.yml
Enabling dependabot for node & python
=> CCM-1230 - Enabling dependabot for node & python

proxies/live/apiproxy/proxies/default.xml, proxies/sandbox/apiproxy/proxies/default.xml, proxies/shared/partials/Partial.Proxy.FaultRules.xml, proxies/shared/partials/Partial.Proxy.PreFlow.xml, proxies/shared/policies/Quota.Global.xml, proxies/shared/policies/Quota.PerApp.xml, proxies/shared/policies/SpikeArrest.Global.xml, proxies/shared/policies/SpikeArrest.PerApp.xml, tests/development/content_types/test_content_type_negotiation.py, tests/development/headers/test_x_correlation_id.py, tests/integration/content_types/test_content_type_negotiation.py, tests/integration/headers/test_x_correlation_id.py, tests/sandbox/content_types/test_content_negotiation.py, tests/sandbox/headers/test_x_correlation_id.py, tests/test_endpoints.py
=> ccm-1138: Add Rate Limiting

Makefile, azure/nightly-zap-scan-pipeline.yml, azure/templates/run-tests.yml
=> ccm:1336: Nightly zap run

.gitignore, Makefile, package.json, postman/CommunicationsManager.Integration.postman_collection.json, scripts/build_postman_environment.py
=> CCM-1413: Add postman check to int

proxies/PROXIES.md, proxies/shared/partials/Partial.Target.FaultRules.xml, sandbox/app.spec.js, sandbox/handlers.js, specification/communications-manager.yaml, tests/development/create_message_batches/test_invalid_routing_plan.py, tests/sandbox/create_message_batches/test_invalid_routing_plan.py
* Swaps check over from 400 to 500 for missing templates
* Adds test cases on for the development environment for checking when the routing plan: 
* has an NHS app template that doesn't exist 
* has a gov notify template that doesn't exist
=> CCM-1479, CCM-1483

tests/development/content_types/test_missing_accept_header.py, tests/development/create_message_batches/test_field_validation.py, tests/development/create_message_batches/test_performance.py, tests/development/create_message_batches/test_success.py, tests/integration/create_message_batches/test_field_validation.py, tests/integration/create_message_batches/test_invalid_routing_plan.py, tests/integration/create_message_batches/test_performance.py, tests/integration/create_message_batches/test_success.py, tests/lib/constants.py, tests/lib/generators.py, tests/sandbox/create_message_batches/test_field_validation.py, tests/sandbox/create_message_batches/test_performance.py, tests/sandbox/create_message_batches/test_success.py
=> ccm-1424: Int tests

tests/test_endpoints.py
=> CCM-1570: Add delay to ping tests

tests/development/create_message_batches/test_field_validation.py, tests/development/create_message_batches/test_invalid_routing_plan.py, tests/development/create_message_batches/test_performance.py, tests/development/create_message_batches/test_success.py, tests/integration/create_message_batches/test_field_validation.py, tests/integration/create_message_batches/test_invalid_routing_plan.py, tests/integration/create_message_batches/test_success.py, tests/lib/generators.py, tests/sandbox/create_message_batches/test_field_validation.py, tests/sandbox/create_message_batches/test_invalid_routing_plan.py, tests/sandbox/create_message_batches/test_performance.py, tests/sandbox/create_message_batches/test_success.py
=> CCM-1614: Update existing tests

azure/nightly-prod-pipeline.yml, azure/templates/run-tests.yml, tests/integration/content_types/test_406_errors.py, tests/integration/content_types/test_415_errors.py, tests/integration/content_types/test_content_type_negotiation.py, tests/integration/create_message_batches/test_field_validation.py, tests/integration/create_message_batches/test_performance.py, tests/integration/create_message_batches/test_success.py, tests/integration/headers/test_cors.py, tests/integration/headers/test_x_correlation_id.py, tests/integration/test_404_errors.py, tests/lib/authentication.py
=> ccm-1471: Prod nightly job

Makefile, tests/lib/authentication.py, tests/lib/constants.py, tests/production/authentication/test_401_errors.py, tests/production/conftest.py, tests/production/content_types/test_406_errors.py, tests/production/content_types/test_415_errors.py, tests/production/content_types/test_content_type_negotiation.py, tests/production/create_message_batches/test_field_validation.py, tests/production/create_message_batches/test_performance.py, tests/production/headers/test_cors.py, tests/production/headers/test_x_correlation_id.py, tests/production/test_404_errors.py
=> CCM-1201: Add production tests

postman/CommunicationsManager.Integration.postman_collection.json, postman/CommunicationsManager.Sandbox.postman_collection.json, proxies/utils/performance/Performance_MessageBatches.Create.Validate.js, specification/communications-manager.yaml
=> CCM-1743 amend sample nhs number

proxies/live/apiproxy/proxies/default.xml, proxies/sandbox/apiproxy/proxies/default.xml, proxies/shared/partials/Partial.Flows.RateLimiting.xml, proxies/shared/partials/Partial.Proxy.PreFlow.xml, scripts/run_locust.sh, tests/lib/assertions.py, tests/locust/test_no_errors.py, tests/locust/test_quota.py, tests/locust/test_spike_arrest.py, tests/locust/user_tasks.py
=> CCM-1723: Fix rate limit application

proxies/shared/policies/AssignMessage.AddCors.xml, proxies/shared/policies/AssignMessage.AddCorsResponse.xml, tests/lib/assertions.py, tests/lib/constants.py
=> CCM-1622: cross origin

Makefile, azure/azure-release-pipeline.yml, azure/nightly-int-qa-pipeline.yml
=> CCM-1680-81: Set up internal QA tests

docs/proxies.md, proxies/live/apiproxy/targets/target.xml, proxies/sandbox/apiproxy/targets/sandbox.xml, proxies/shared/partials/Partial.Flows.CreateMessageEndpoint.xml, proxies/shared/policies/AssignMessage.Messages.Create.Request.xml, proxies/shared/policies/AssignMessage.Messages.Create.Response.xml, proxies/shared/policies/JavaScript.Messages.Create.Request.xml, proxies/shared/policies/JavaScript.Messages.Create.Response.xml, proxies/shared/policies/JavaScript.Messages.Create.Validate.xml, proxies/shared/resources/jsc/Messages.Create.Request.js, proxies/shared/resources/jsc/Messages.Create.Response.js, proxies/shared/resources/jsc/Messages.Create.Validate.js
Adds basic scaffolding for the POST /v1/messages endpoint.
=> CCM-1836 - POST /v1/messages

azure/nightly-zap-scan-pipeline.yml
=> CCM-1834: Stagger nightly prod runs

Makefile, tests/development/content_types/test_content_type_negotiation.py, tests/development/content_types/test_missing_accept_header.py, tests/development/headers/test_x_correlation_id.py, tests/integration/content_types/test_content_type_negotiation.py, tests/integration/headers/test_x_correlation_id.py, tests/lib/__init__.py, tests/lib/assertions.py, tests/lib/constants.py, tests/lib/error_handler.py, tests/production/content_types/test_content_type_negotiation.py, tests/production/headers/test_x_correlation_id.py, tests/sandbox/content_types/test_content_negotiation.py, tests/sandbox/headers/test_x_correlation_id.py, tests/sandbox/test_429_errors.py, tests/test_endpoints.py
=> CCM-1866: Handle unexpected 504

docs/proxies.md, docs/tests/sandbox/index.md, docs/tests/sandbox/post_v1_message-batches/index.md, docs/tests/sandbox/post_v1_message-batches/retry_too_early.md, proxies/shared/partials/Partial.Target.FaultRules.xml, proxies/shared/partials/Partial.Target.PreFlowRequest.xml, proxies/shared/policies/RaiseFault.425RetryTooEarly.xml, sandbox/app.spec.js, sandbox/handlers.js, specification/communications-manager.yaml, specification/schemas/RetryTooEarlyResponse.yaml, specification/schemas/enums/EnumErrorRetryTooEarly.yaml, tests/docs/sandbox/post_v1_message-batches/index.rst, tests/docs/sandbox/post_v1_message-batches/retry_too_early.rst, tests/lib/constants.py, tests/lib/generators.py, tests/sandbox/create_message_batches/test_retry_too_early.py
Updates the API to support 425 responses.
=> CCM-1606: handle 425 errors

azure/nightly-prod-pipeline.yml
=> CCM-1750-prod

specification/communications-manager.yaml
This updates the specification to make it clear the product is in beta
=> CCM-2011: update specification to say product is in beta

azure/nightly-int-dev-pipeline.yml, azure/nightly-int-qa-pipeline.yml, azure/nightly-int-sandbox-pipeline.yml, azure/nightly-integration-pipeline.yml, azure/nightly-prod-pipeline.yml, azure/nightly-zap-scan-pipeline.yml, azure/templates/run-tests.yml, azure/templates/teams-alert-setup.yml, azure/templates/teams-alert.yml
=> CCM-1620: Post test failures to teams

azure/periodic-mtls-pipeline.yml
=> CCM-1621: Add teams alert to mtls job

azure/periodic-mtls-pipeline.yml
=> CCM-2124: Add timeout to mtls

tests/lib/assertions.py, tests/sandbox/messages/create_messages/test_success.py
=> CCM-2325: Version tests

docs/tests/index.md, docs/tests/sandbox/get_v1_messages_message-id/happy_path.md, docs/tests/sandbox/index.md, tests/docs/partials/happy_path/test_200_get_message_valid_response_bodies.rst, tests/docs/sandbox/index.rst, tests/lib/assertions.py, tests/sandbox/messages/get_message/test_success.py
=> CCM-1897: Response body test

package-lock.json, package.json
=> CCM-1744: remove apigeetool

docs/tests/sandbox/get_v1_messages_message-id/404.md, docs/tests/sandbox/get_v1_messages_message-id/index.md, docs/tests/sandbox/index.md, tests/docs/partials/not_found/test_404_not_found_single_method.rst, tests/docs/sandbox/get_v1_messages_message-id/404.rst, tests/docs/sandbox/get_v1_messages_message-id/index.rst, tests/sandbox/messages/get_message/test_404.py
=> CCM-1898: get message 404

tests/development/messages/create_message/test_invalid_routing_plan.py
=> CCM-1660: Add development 500 routing plan tests

tests/development/messages/create_message/test_success.py, tests/docs/partials/happy_path/test_201_messages_valid_accept_headers.rst, tests/docs/partials/happy_path/test_201_messages_valid_content_type_headers.rst, tests/docs/partials/happy_path/test_201_messages_valid_dob.rst, tests/docs/partials/happy_path/test_201_messages_valid_nhs_number.rst, tests/docs/partials/happy_path/test_201_messages_without_dob.rst, tests/lib/assertions.py
=> CCM-2310: Add success tests for dev for /v1/messages

docs/tests/index.md, docs/tests/integration/index.md, docs/tests/integration/post_v1_messages/happy_path.md, docs/tests/integration/post_v1_messages/index.md, tests/docs/integration/index.rst, tests/docs/integration/post_v1_messages/happy_path.rst, tests/docs/integration/post_v1_messages/index.rst, tests/integration/messages/create_messages/test_success.py
=> CCM-1666: Add int 201 tests

docs/tests/integration/index.md, docs/tests/integration/post_v1_messages/index.md, docs/tests/integration/post_v1_messages/validation.md, tests/docs/integration/post_v1_messages/index.rst, tests/docs/integration/post_v1_messages/validation.rst, tests/integration/messages/create_messages/test_field_validation.py
=> CCM-1665: Add field validation tests for int

tests/sandbox/message_batches/create_message_batches/test_field_validation.py
=> CCM-2431: Remove sandbox auth

docs/tests/development/post_v1_message-batches/happy_path.md, docs/tests/development/post_v1_messages/happy_path.md, docs/tests/integration/post_v1_message-batches/happy_path.md, docs/tests/integration/post_v1_messages/happy_path.md, tests/development/message_batches/create_message_batches/test_success.py, tests/development/messages/create_messages/test_success.py, tests/docs/partials/happy_path/test_201_message_batches_request_idempotency.rst, tests/docs/partials/happy_path/test_201_messages_request_idempotency.rst, tests/integration/message_batches/create_message_batches/test_success.py, tests/integration/messages/create_messages/test_success.py, tests/lib/assertions.py
=> ccm-2444: idempotency tests

postman/CommunicationsManager.Integration.postman_collection.json, postman/CommunicationsManager.Sandbox.postman_collection.json
=> CCM-1640: Add 425 test to postman collection

sandbox/messages/2WL3qFTEFM0qMY8xjRbt1LIKCzM.json, sandbox/messages/2WL3wwFhpZ6blJNIoh747bDEFNv.json, sandbox/messages/2WL3ydEEk37IzREoWRhuAdolFCE.json, sandbox/messages/2WL3zxCY9e5vm2VP1ZfYMb53WPF.json, sandbox/messages/2WL44QP7vrKxKKBZdTtUQoB2bWl.json, sandbox/messages/2WL45YuHOLATvC3GspEu0oSioux.json, sandbox/messages/2WL4GEeFVxXG9S57nRlefBwwKxp.json, sandbox/messages/2WL4JXrfauCaQnSFbAujoImSKwo.json, sandbox/messages/2WL4JtCiOe7l2TT4szwPjNJah3z.json, sandbox/messages/2WL4LuyNMtoGAsJQIpTxZLl8e3e.json, sandbox/messages/2WL4MOuSeCTODDAScFG7KIq9a5r.json, sandbox/messages/2WL4QcKGjNHvHFQeKgYbapZJGHK.json, sandbox/messages/2WL4W9RgbuLLByXdR77H8vjKSDd.json, sandbox/messages/2WL4cPfBRuPKa44JxhyXYf2kr1E.json, sandbox/messages/2WL4g2f7GQ2F9HZmgonIFiXAPku.json, sandbox/messages/2WL4ibGoigirgbH4yQwqbPaJXyQ.json, sandbox/messages/2WL4khXn32dOOj4bB4bi8Tkllrq.json, sandbox/messages/2WL4mvx6eBva8dcIK60VEGIfcgZ.json, sandbox/messages/2WL4pcpmKxYYblm3PSKVEqcmEPX.json, sandbox/messages/2WL4vHFZzInmaYwq6HRNDqTX8dH.json, sandbox/messages/2WL4xcWKvz4F32g0htBEl8DINzn.json, sandbox/messages/2WL50w41YaZXcyFCNT346LY8rlz.json, sandbox/messages/2WL54x0XQjCbWeE5lN0DKQZcokU.json, sandbox/messages/2WL5TWl7F7PondWbZ1vctlEtOZ3.json, sandbox/messages/2WL5eDefrbW31uw1il84WdF8ndH.json, sandbox/messages/2WL5eYSWGzCHlGmzNxuqVusPxDg.json, sandbox/messages/2WL5f8j4XVxUPgd3OOqXVYvVFIW.json, sandbox/messages/2WL5qbEa7TzSWZXU2IAOCCrLXVL.json
Implements CCM-2411, updates sample messages to align with documentation
=> CCM-2411 amend metadata on sandbox get message endpoint

postman/CommunicationsManager.Integration.postman_collection.json, postman/CommunicationsManager.Sandbox.postman_collection.json
=> CCM-1671: Postman - Sandbox Post Message Collection

tests/lib/constants/constants.py
=> CCM-2616: Add get message endpoint to valid endpoints

postman/CommunicationsManager.Integration.postman_collection.json
=> CCM-1672: Postman - integration - POST /v1/messages

docs/tests/development/get_v1_messages/happy_path.md, docs/tests/development/get_v1_messages/index.md, docs/tests/development/index.md, docs/tests/index.md, tests/development/messages/get_message/test_success.py, tests/docs/development/get_v1_messages/happy_path.rst, tests/docs/development/get_v1_messages/index.rst, tests/docs/development/index.rst, tests/docs/partials/happy_path/test_200_get_message_cascade.rst, tests/docs/partials/happy_path/test_200_get_message_failed.rst, tests/docs/partials/happy_path/test_200_get_message_pending_enrichment.rst, tests/docs/partials/happy_path/test_200_get_message_sending.rst, tests/docs/partials/happy_path/test_200_get_message_successful.rst, tests/lib/assertions.py, tests/lib/constants/messages_paths.py
=> CCM-2572: Add 200 GET message tests on development

docs/tests/development/get_v1_messages/404.md, docs/tests/development/get_v1_messages/index.md, docs/tests/development/index.md, tests/development/messages/get_message/test_404.py, tests/docs/development/get_v1_messages/404.rst, tests/docs/development/get_v1_messages/index.rst, tests/docs/partials/not_found/test_message_id_not_belonging_to_client_id.rst, tests/docs/partials/not_found/test_message_id_that_does_not_exist.rst
=> CCM-2575: Add 404 tests for dev

sandbox/messages/2WL3qFTEFM0qMY8xjRbt1LIKCzM.json, sandbox/messages/2WL3wwFhpZ6blJNIoh747bDEFNv.json, sandbox/messages/2WL3ydEEk37IzREoWRhuAdolFCE.json, sandbox/messages/2WL3zxCY9e5vm2VP1ZfYMb53WPF.json, sandbox/messages/2WL44QP7vrKxKKBZdTtUQoB2bWl.json, sandbox/messages/2WL45YuHOLATvC3GspEu0oSioux.json, sandbox/messages/2WL4GEeFVxXG9S57nRlefBwwKxp.json, sandbox/messages/2WL4JXrfauCaQnSFbAujoImSKwo.json, sandbox/messages/2WL4JtCiOe7l2TT4szwPjNJah3z.json, sandbox/messages/2WL4LuyNMtoGAsJQIpTxZLl8e3e.json, sandbox/messages/2WL4MOuSeCTODDAScFG7KIq9a5r.json, sandbox/messages/2WL4QcKGjNHvHFQeKgYbapZJGHK.json, sandbox/messages/2WL4W9RgbuLLByXdR77H8vjKSDd.json, sandbox/messages/2WL4cPfBRuPKa44JxhyXYf2kr1E.json, sandbox/messages/2WL4g2f7GQ2F9HZmgonIFiXAPku.json, sandbox/messages/2WL4ibGoigirgbH4yQwqbPaJXyQ.json, sandbox/messages/2WL4khXn32dOOj4bB4bi8Tkllrq.json, sandbox/messages/2WL4mvx6eBva8dcIK60VEGIfcgZ.json, sandbox/messages/2WL4pcpmKxYYblm3PSKVEqcmEPX.json, sandbox/messages/2WL4vHFZzInmaYwq6HRNDqTX8dH.json, sandbox/messages/2WL4xcWKvz4F32g0htBEl8DINzn.json, sandbox/messages/2WL50w41YaZXcyFCNT346LY8rlz.json, sandbox/messages/2WL54x0XQjCbWeE5lN0DKQZcokU.json, sandbox/messages/2WL5TWl7F7PondWbZ1vctlEtOZ3.json, sandbox/messages/2WL5eDefrbW31uw1il84WdF8ndH.json, sandbox/messages/2WL5eYSWGzCHlGmzNxuqVusPxDg.json, sandbox/messages/2WL5f8j4XVxUPgd3OOqXVYvVFIW.json, sandbox/messages/2WL5qbEa7TzSWZXU2IAOCCrLXVL.json
=> CCM-2573: Remove 'updated' status from sandbox

sandbox/messages/2WL3qFTEFM0qMY8xjRbt1LIKCzM.json, sandbox/messages/2WL3wwFhpZ6blJNIoh747bDEFNv.json, sandbox/messages/2WL3ydEEk37IzREoWRhuAdolFCE.json, sandbox/messages/2WL3zxCY9e5vm2VP1ZfYMb53WPF.json, sandbox/messages/2WL44QP7vrKxKKBZdTtUQoB2bWl.json, sandbox/messages/2WL45YuHOLATvC3GspEu0oSioux.json, sandbox/messages/2WL4GEeFVxXG9S57nRlefBwwKxp.json, sandbox/messages/2WL4JXrfauCaQnSFbAujoImSKwo.json, sandbox/messages/2WL4JtCiOe7l2TT4szwPjNJah3z.json, sandbox/messages/2WL4LuyNMtoGAsJQIpTxZLl8e3e.json, sandbox/messages/2WL4MOuSeCTODDAScFG7KIq9a5r.json, sandbox/messages/2WL4QcKGjNHvHFQeKgYbapZJGHK.json, sandbox/messages/2WL4W9RgbuLLByXdR77H8vjKSDd.json, sandbox/messages/2WL4cPfBRuPKa44JxhyXYf2kr1E.json, sandbox/messages/2WL4g2f7GQ2F9HZmgonIFiXAPku.json, sandbox/messages/2WL4ibGoigirgbH4yQwqbPaJXyQ.json, sandbox/messages/2WL4khXn32dOOj4bB4bi8Tkllrq.json, sandbox/messages/2WL4mvx6eBva8dcIK60VEGIfcgZ.json, sandbox/messages/2WL4pcpmKxYYblm3PSKVEqcmEPX.json, sandbox/messages/2WL4vHFZzInmaYwq6HRNDqTX8dH.json, sandbox/messages/2WL4xcWKvz4F32g0htBEl8DINzn.json, sandbox/messages/2WL50w41YaZXcyFCNT346LY8rlz.json, sandbox/messages/2WL54x0XQjCbWeE5lN0DKQZcokU.json, sandbox/messages/2WL5TWl7F7PondWbZ1vctlEtOZ3.json, sandbox/messages/2WL5eDefrbW31uw1il84WdF8ndH.json, sandbox/messages/2WL5eYSWGzCHlGmzNxuqVusPxDg.json, sandbox/messages/2WL5f8j4XVxUPgd3OOqXVYvVFIW.json, sandbox/messages/2WL5qbEa7TzSWZXU2IAOCCrLXVL.json, tests/lib/assertions.py
=> CCM-2613: update sandbox routing plan field

sandbox/messages/2WL3qFTEFM0qMY8xjRbt1LIKCzM.json, sandbox/messages/2WL3wwFhpZ6blJNIoh747bDEFNv.json, sandbox/messages/2WL3ydEEk37IzREoWRhuAdolFCE.json, sandbox/messages/2WL3zxCY9e5vm2VP1ZfYMb53WPF.json, sandbox/messages/2WL44QP7vrKxKKBZdTtUQoB2bWl.json, sandbox/messages/2WL45YuHOLATvC3GspEu0oSioux.json, sandbox/messages/2WL4GEeFVxXG9S57nRlefBwwKxp.json, sandbox/messages/2WL4JXrfauCaQnSFbAujoImSKwo.json, sandbox/messages/2WL4JtCiOe7l2TT4szwPjNJah3z.json, sandbox/messages/2WL4LuyNMtoGAsJQIpTxZLl8e3e.json, sandbox/messages/2WL4MOuSeCTODDAScFG7KIq9a5r.json, sandbox/messages/2WL4W9RgbuLLByXdR77H8vjKSDd.json, sandbox/messages/2WL4vHFZzInmaYwq6HRNDqTX8dH.json, sandbox/messages/2WL4xcWKvz4F32g0htBEl8DINzn.json, sandbox/messages/2WL50w41YaZXcyFCNT346LY8rlz.json, sandbox/messages/2WL54x0XQjCbWeE5lN0DKQZcokU.json, sandbox/messages/2WL5TWl7F7PondWbZ1vctlEtOZ3.json, sandbox/messages/2WL5eDefrbW31uw1il84WdF8ndH.json, sandbox/messages/2WL5eYSWGzCHlGmzNxuqVusPxDg.json, sandbox/messages/2WL5f8j4XVxUPgd3OOqXVYvVFIW.json, sandbox/messages/2WL5qbEa7TzSWZXU2IAOCCrLXVL.json
sandbox messages references to versionID replaced by version
=> CCM-2543: refactor versionId to version

sandbox/messages/2WL3qFTEFM0qMY8xjRbt1LIKCzM.json, sandbox/messages/2WL3wwFhpZ6blJNIoh747bDEFNv.json, sandbox/messages/2WL3ydEEk37IzREoWRhuAdolFCE.json, sandbox/messages/2WL3zxCY9e5vm2VP1ZfYMb53WPF.json, sandbox/messages/2WL44QP7vrKxKKBZdTtUQoB2bWl.json, sandbox/messages/2WL45YuHOLATvC3GspEu0oSioux.json, sandbox/messages/2WL4GEeFVxXG9S57nRlefBwwKxp.json, sandbox/messages/2WL4JXrfauCaQnSFbAujoImSKwo.json, sandbox/messages/2WL4JtCiOe7l2TT4szwPjNJah3z.json, sandbox/messages/2WL4LuyNMtoGAsJQIpTxZLl8e3e.json, sandbox/messages/2WL4MOuSeCTODDAScFG7KIq9a5r.json, sandbox/messages/2WL4QcKGjNHvHFQeKgYbapZJGHK.json, sandbox/messages/2WL4W9RgbuLLByXdR77H8vjKSDd.json, sandbox/messages/2WL4cPfBRuPKa44JxhyXYf2kr1E.json, sandbox/messages/2WL4g2f7GQ2F9HZmgonIFiXAPku.json, sandbox/messages/2WL4ibGoigirgbH4yQwqbPaJXyQ.json, sandbox/messages/2WL4khXn32dOOj4bB4bi8Tkllrq.json, sandbox/messages/2WL4mvx6eBva8dcIK60VEGIfcgZ.json, sandbox/messages/2WL4pcpmKxYYblm3PSKVEqcmEPX.json, sandbox/messages/2WL4vHFZzInmaYwq6HRNDqTX8dH.json, sandbox/messages/2WL4xcWKvz4F32g0htBEl8DINzn.json, sandbox/messages/2WL50w41YaZXcyFCNT346LY8rlz.json, sandbox/messages/2WL54x0XQjCbWeE5lN0DKQZcokU.json, sandbox/messages/2WL5TWl7F7PondWbZ1vctlEtOZ3.json, sandbox/messages/2WL5eDefrbW31uw1il84WdF8ndH.json, sandbox/messages/2WL5eYSWGzCHlGmzNxuqVusPxDg.json, sandbox/messages/2WL5f8j4XVxUPgd3OOqXVYvVFIW.json, sandbox/messages/2WL5qbEa7TzSWZXU2IAOCCrLXVL.json, tests/lib/assertions.py
=> CCM-2787: Update sandbox responses

azure/azure-release-pipeline.yml
=> CCM-2126: Add ref environment

proxies/shared/policies/AssignMessage.MessageBatches.Create.Response.xml, proxies/shared/policies/ExtractVariables.MessageBatches.Create.Response.xml, sandbox/__test__/batch_send.spec.js, sandbox/handlers/batch_send.js, tests/development/content_types/test_missing_accept_header.py, tests/development/message_batches/create_message_batches/test_success.py, tests/integration/message_batches/create_message_batches/test_success.py, tests/lib/assertions.py, tests/sandbox/message_batches/create_message_batches/test_performance.py, tests/sandbox/message_batches/create_message_batches/test_success.py
Return the routing plan id and version on the send batch endpoint.
=> CCM-2327: send batch - expose routing plan

.github/pull_request_template.md
adds tester approval as a checklist item
and bumps required number of reviews from 1 to 2 (requested by Phil)
=> adds tester approval to checklist

docs/tests/end_to_end/gov_notify/index.md, docs/tests/end_to_end/gov_notify/sms.md, docs/tests/end_to_end/index.md, tests/docs/end_to_end/gov_notify/index.rst, tests/docs/end_to_end/gov_notify/sms.rst, tests/docs/partials/happy_path/test_sms_end_to_end.rst, tests/end_to_end/test_sms.py, tests/lib/assertions.py
=> CCM-1691: Test SMS end to end

scripts/calculate_version.py, tests/development/messages/get_message/test_success.py
Release 4.11.1
Hotpatch including CCM-3098 and CCM-3210
=> Release 4.11.1

docs/tests/end_to_end/gov_notify/email.md, docs/tests/end_to_end/gov_notify/index.md, docs/tests/end_to_end/gov_notify/letter.md, docs/tests/end_to_end/gov_notify/sms.md, docs/tests/end_to_end/index.md, tests/docs/end_to_end/gov_notify/index.rst, tests/docs/end_to_end/gov_notify/letter.rst, tests/docs/partials/happy_path/test_email_end_to_end.rst, tests/docs/partials/happy_path/test_letter_end_to_end.rst, tests/docs/partials/happy_path/test_sms_end_to_end.rst, tests/end_to_end/test_email.py, tests/end_to_end/test_letter.py, tests/lib/__init__.py, tests/lib/assertions.py, tests/lib/helper.py
=> CCM-1693: Add letter e2e tests

docs/tests/integration/post_v1_messages/happy_path.md, docs/tests/sandbox/post_v1_messages/happy_path.md, tests/integration/messages/create_messages/test_success.py, tests/lib/assertions.py, tests/sandbox/messages/create_messages/test_success.py
=> CCM-3271: Fix int test version ID

docs/tests/end_to_end/index.md, docs/tests/end_to_end/nhsapp/index.md, docs/tests/end_to_end/nhsapp/nhsapp.md, docs/tests/index.md, tests/docs/end_to_end/index.rst, tests/docs/end_to_end/nhsapp/index.rst, tests/docs/end_to_end/nhsapp/nhsapp.rst, tests/docs/partials/happy_path/test_nhsapp_end_to_end.rst, tests/end_to_end/test_nhsapp.py, tests/lib/generators.py, tests/lib/helper.py
=> CCM-1694: NHS App e2e

RELEASING.md
=> Release candidate v4.13.0

sandbox/index.js
The node application in sandbox was failing to run. This resulted in failures in the pipeline integration tests.
=> CCM-3723 fix broken sandbox

Makefile, azure/nightly-internal-dev-end-to-end-pipeline.yml, azure/nightly-uat-end-to-end-pipeline.yml, azure/templates/run-tests.yml, docs/tests/end_to_end/gov_notify/email.md, docs/tests/end_to_end/gov_notify/letter.md, docs/tests/end_to_end/gov_notify/sms.md, tests/docs/partials/happy_path/test_email_end_to_end_internal_dev.rst, tests/docs/partials/happy_path/test_email_end_to_end_uat.rst, tests/docs/partials/happy_path/test_letter_end_to_end_internal_dev.rst, tests/docs/partials/happy_path/test_letter_end_to_end_uat.rst, tests/docs/partials/happy_path/test_sms_end_to_end_internal_dev.rst, tests/docs/partials/happy_path/test_sms_end_to_end_uat.rst, tests/end_to_end/test_email.py, tests/end_to_end/test_letter.py, tests/end_to_end/test_sms.py, tests/lib/generators.py
=> CCM-3357: Add Gov Notify end to end tests

proxies/shared/resources/jsc/Messages.Create.Validate.js, tests/lib/generators.py
Correct c&p mistake breaking pre-request validation
=> CCM-3966: Fix odsCode validation

specification/callbacks/message-subscription-openapi-spec.json, specification/callbacks/message_subscriptions.yaml, specification/communications-manager.yaml, specification/schemas/components/CallbackRequest.yaml
added callbacks section to api docs
=> CCM-2533: Added spec file for callbacks

proxies/sandbox/apiproxy/targets/sandbox.xml, proxies/shared/partials/Partial.Flows.GetNhsAppAccountsEndpoint.xml, proxies/shared/policies/AssignMessage.NhsAppAccounts.Get.Request.xml, proxies/shared/policies/AssignMessage.NhsAppAccounts.Get.Response.xml, proxies/shared/policies/ExtractVariables.NhsAppAccounts.Get.Request.xml, proxies/shared/policies/JavaScript.Messages.Create.Response.xml, proxies/shared/policies/JavaScript.NhsAppAccounts.Get.Response.xml, proxies/shared/policies/JavaScript.NhsAppAccounts.Get.Validate.xml, proxies/shared/resources/jsc/Messages.Create.Response.js, proxies/shared/resources/jsc/NhsAppAccounts.Get.Validate.js, proxies/shared/resources/jsc/NhsAppAccounts.Ok.Response.js, proxies/shared/resources/jsc/Routing.CheckValid.js, proxies/shared/resources/jsc/helpers/responseHelpers.js
=> CCM-3796: Added new proxy endpoint to integrate with NHS app

azure/azure-build-pipeline.yml, azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, azure/nightly-int-dev-pipeline.yml, azure/nightly-int-qa-pipeline.yml, azure/nightly-int-sandbox-pipeline.yml, azure/nightly-integration-pipeline.yml, azure/nightly-internal-dev-end-to-end-pipeline.yml, azure/nightly-prod-pipeline.yml, azure/nightly-prod-sandbox-pipeline.yml, azure/nightly-uat-end-to-end-pipeline.yml, azure/nightly-zap-scan-pipeline.yml
We are currently using a version of the APIM utils repo on the `edge-fixed` branch due to an issue on the `edge` branch which has now been resolved. This PR is to switch to using the `edge` branch again.
=> CCM-1422: point to edge and not edge-fixed ref

tests/development/messages/create_messages/test_success.py, tests/integration/messages/create_messages/test_success.py, tests/lib/assertions.py, tests/sandbox/messages/create_messages/test_success.py
* Fixes existing tests to accept ref URL
=> CCM-4958: Fix ref link assertion tests

poetry.lock
https://nhsd-jira.digital.nhs.uk/browse/CCM-4988
Updating python package versions in line with Dependobot reports
=> CCM-4988: updated poetry.lock to update python packages

docs/tests/integration/post_v1_messages/happy_path.md, tests/integration/messages/create_messages/test_success.py, tests/sandbox/messages/create_messages/test_success.py
Updates the test naming for tests that were incorrectly marked as batch tests.
=> CCM-2834_update_test_naming

specification/schemas/enums/ErrorInvalidValue.yaml, specification/schemas/responses/errors/message_batches/UnableToProcessBatch.yaml, specification/schemas/responses/errors/messages/UnableToProcessMessage.yaml, specification/schemas/types/LinksErrorNHSNumber.yaml
=> v4.19.0 to master

tests/lib/helper.py
=> CCM-5433: Update NHS App UAT playwright tests with updated text

Makefile, docs/tests/integration/get_channels_nhsapp_accounts/happy_path.md, pytest.ini, tests/development/nhsapp_accounts/test_success.py, tests/integration/nhsapp_accounts/test_success.py
=> CCM-5461: Remove multiple page tests from internal-qa and int

specification/documentation/GetMessage.md, specification/schemas/enums/SupplierStatus.yaml, specification/schemas/responses/MessageResponse.yaml
Added supplierStatus information to GET message status endpoint documentation
=> CCM-4956: Added supplierStatus information to GET message status endpoint documentation

tests/lib/helper.py
=> CCM-5627: Update tests to reflect AOS

specification/schemas/enums/ErrorInvalidNHSNumber.yaml, specification/schemas/responses/errors/message_batches/UnableToProcessBatch.yaml, specification/schemas/responses/errors/messages/UnableToProcessMessage.yaml
updated response body for 400 errors in send message and send batch docs
=> CCM-5469: updated response body for 400 errors in send message and send batch docs

azure/azure-build-pipeline.yml, azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, azure/nightly-int-dev-pipeline.yml, azure/nightly-int-qa-pipeline.yml, azure/nightly-int-sandbox-pipeline.yml, azure/nightly-integration-pipeline.yml, azure/nightly-internal-dev-end-to-end-pipeline.yml, azure/nightly-prod-pipeline.yml, azure/nightly-prod-sandbox-pipeline.yml, azure/nightly-uat-end-to-end-pipeline.yml, azure/nightly-zap-scan-pipeline.yml, azure/periodic-mtls-pipeline.yml
=> CCM-1757: Repoint service account

postman/CommunicationsManager.Integration.postman_collection.json, postman/CommunicationsManager.Sandbox.postman_collection.json
added postman collection for NHS App Account
=> CCM-3800: added postman collection for NHS App Account

package-lock.json, package.json
bump redocly version to 1.10.6
=> CCM-4117: bump redocly version to 1.10.6

package-lock.json, package.json
bumped @types/node to version 20.12.2
=> CCM-4119: bumped @types/node to version 20.12.2

tests/development/content_types/test_406_errors.py, tests/development/content_types/test_415_errors.py, tests/development/test_404_errors.py, tests/integration/content_types/test_406_errors.py, tests/integration/content_types/test_415_errors.py, tests/integration/test_404_errors.py, tests/sandbox/content_types/test_406_errors.py, tests/sandbox/content_types/test_415_errors.py, tests/sandbox/test_404_errors.py
=> CCM-5506: Update 406 415 Test scenarios

tests/docs/sandbox/generic/timeouts.rst, tests/sandbox/test_408_errors.py, tests/sandbox/test_504_errors.py
=> CCM-5505: Split timeout tests into their own files

CONTRIBUTING.md, package-lock.json
The repositories merge strategy is going to change to `Squash and merge` only. This change updates the documentation to reflect this.
=> CCM-4908 Change merge strategy

Makefile, package.json, sandbox/__test__/get_message.spec.js, sandbox/__test__/nhsapp_accounts.spec.js, sandbox/handlers/get_message.js, sandbox/handlers/nhsapp_accounts.js, scripts/linter/base.js
- Moved `base.js` to `scripts/linter/base.js`
- Resolved the remaining linting issues
- `lint-js` added to the `make lint` command
=> CCM-5959: Resolve remaining linting issues

specification/documentation/APIDescription.md, specification/schemas/enums/SupplierStatus.yaml
added gukn supplierStatus definitions to docs
=> CCM-3755/CCM-3756: added gukn supplierStatus definitions to docs

docs/tests/development/get_channels_nhsapp_accounts/502.md, docs/tests/integration/get_channels_nhsapp_accounts/400.md, docs/tests/production/get_channels_nhsapp_accounts/400.md, docs/tests/sandbox/get_channels_nhsapp_accounts/502.md, tests/development/nhsapp_accounts/test_502.py, tests/integration/nhsapp_accounts/test_400.py, tests/production/nhsapp_accounts/test_400.py, tests/sandbox/nhsapp_accounts/test_502.py
=> CCM-6036: Fix test documentation

proxies/shared/partials/Partial.Target.FaultRules.xml, proxies/shared/policies/ExtractVariables.ErrorDetails.xml, proxies/shared/policies/ExtractVariables.ErrorMessage.xml, proxies/shared/policies/JavaScript.EnhanceErrorDetails.xml, proxies/shared/policies/RaiseFault.GenericErrorDetails.xml, proxies/shared/resources/jsc/EnhanceErrorDetails.js, sandbox/__test__/messages.spec.js, sandbox/handlers/config.js, sandbox/handlers/messages.js, sandbox/handlers/utils.js, tests/lib/authentication.py
This is the merge request to kick off the 4.25.0 release
=> V4.25.0 Release

specification/callbacks/channel-subscription-openapi-spec.json, specification/communications-manager.yaml, specification/schemas/components/MessageStatus.yaml, specification/schemas/components/SupplierStatus.yaml, specification/schemas/types/Page.yaml
=> CCM-5786: Fix schema validation errors caused by invalid type definitions

package-lock.json, package.json
=> Update @redocly/cli to 1.25.3

sandbox/package-lock.json, sandbox/package.json
Updates following packages:
- `uuid`
- `c8`
- `chai`
- `mocha`
- `nodemon`
=> CCM-6418: update sandbox node deps

tests/lib/helper.py
Adjust the timeout for the test function that appears to be failing on the nightly test
=> CCM-6362: adjust nightly UI test timeouts

specification/documentation/APIDescription.md, specification/responses/4xx/message_batches/400_UnableToProcessMessageBatch.yaml, specification/responses/4xx/messages/400_UnableToProcessMessage.yaml, specification/schemas/components/Recipient.yaml, specification/schemas/responses/errors/message_batches/UnableToProcessBatch.yaml, specification/schemas/responses/errors/messages/UnableToProcessMessage.yaml, specification/schemas/types/ErrorPointer.yaml
Updating the API documentation for the new override contact details feature.
Bloomreach link: https://cms-training2.nhsd.io/cms/content/path/content/documents/corporate-website/developer/api-catalogue/nhs-notify/iaho3
=> CCM-5394 Contact details API documentation

specification/documentation/APIDescription.md
Added routing config IDs for SMS and Email free text templates
=> CCM-6457: Update API docs for SMS/Email free text

tests/lib/assertions.py
Adds assertion to validate that cascadeType and cascadeOrder are being populated.
=> CCM-6693: update get message endpoint api 

sandbox/messages/2WL3qFTEFM0qMY8xjRbt1LIKCzM.json, sandbox/messages/2WL3wwFhpZ6blJNIoh747bDEFNv.json, sandbox/messages/2WL3ydEEk37IzREoWRhuAdolFCE.json, sandbox/messages/2WL3zxCY9e5vm2VP1ZfYMb53WPF.json, sandbox/messages/2WL44QP7vrKxKKBZdTtUQoB2bWl.json, sandbox/messages/2WL45YuHOLATvC3GspEu0oSioux.json, sandbox/messages/2WL4GEeFVxXG9S57nRlefBwwKxp.json, sandbox/messages/2WL4JXrfauCaQnSFbAujoImSKwo.json, sandbox/messages/2WL4JtCiOe7l2TT4szwPjNJah3z.json, sandbox/messages/2WL4LuyNMtoGAsJQIpTxZLl8e3e.json, sandbox/messages/2WL4MOuSeCTODDAScFG7KIq9a5r.json, sandbox/messages/2WL4W9RgbuLLByXdR77H8vjKSDd.json, sandbox/messages/2WL4vHFZzInmaYwq6HRNDqTX8dH.json, sandbox/messages/2WL4xcWKvz4F32g0htBEl8DINzn.json, sandbox/messages/2WL50w41YaZXcyFCNT346LY8rlz.json, sandbox/messages/2WL54x0XQjCbWeE5lN0DKQZcokU.json, sandbox/messages/2WL5TWl7F7PondWbZ1vctlEtOZ3.json, sandbox/messages/2WL5eDefrbW31uw1il84WdF8ndH.json, sandbox/messages/2WL5eYSWGzCHlGmzNxuqVusPxDg.json, sandbox/messages/2WL5f8j4XVxUPgd3OOqXVYvVFIW.json, sandbox/messages/2WL5qbEa7TzSWZXU2IAOCCrLXVL.json, sandbox/messages/2bBBpsiMl2rnQt99qm6JLZ6w1vq.json, sandbox/messages/2n7C5wdJ9JSOSeCJTyd50GvtZeR.json
- Adds new parallel send GET message status response
- Updates existing GET message status responses to include cascadeType and cascadeOrder fields.
=> CCM-6696: add parallel send response to sandbox

tests/production/message_batches/create_message_batches/test_too_large.py
Fixes a compile time error in tests/production/message_batches/create_message_batches/test_too_large.py.
Before change:
After change:
=> CCM-7212 Fix production test file compile error

specification/callbacks/message_status.yaml, specification/schemas/components/SupplierStatus.yaml, specification/schemas/enums/CascadeType.yaml, specification/schemas/responses/MessageResponse.yaml, specification/snippets/CascadeOrder.yaml
Changes deployed to my todr3 Bloomreach environment
=> CCM-6695: Added API docs for cascadeType and cascadeOrder (Parallel Send)

tests/development/message_batches/create_message_batches/test_field_validation.py
This pull requests amends an issue that was introduced by rebasing and missed during the merge process
=> CCM-6416: corrects data for personalisation test cases for batch send

docs/tests/production/post_v1_message-batches/validation.md, docs/tests/production/post_v1_messages/validation.md, tests/production/message_batches/create_message_batches/test_field_validation.py, tests/production/messages/create_messages/test_field_validation.py
=> CCM-7443: Remove too large personalisation tests

specification/schemas/components/Recipient.yaml
Removed references to validation libraries from API docs
=> CCM-7256: Removed references to validation libraries from API docs

postman/CommunicationsManager.Sandbox.postman_collection.json
=> CCM-6384: Update Sandbox Collection with 403 Service Ban Example

specification/schemas/types/RoutingPlan.yaml
=> CCM-7052\CCM-7053: Update API documentation

specification/documentation/APIDescription.md
Changed wording to add mention of callbacks.
=> CCM-7660: Update wording of "additive non-breaking" changes disclaimer

README.md
Makes sure installation of get_token is covered in setup instructions
=> CCM-5199: update readme

.tool-versions, README.md, scripts/mtls/disable_mtls.sh, scripts/repoint-frontend/README.md, scripts/repoint-frontend/repoint_frontend.sh, scripts/repoint-frontend/update_proxy_files.py, specification/documentation/APIDescription.md, specification/schemas/components/SupplierStatus.yaml
=> CCM-7742: release v4.31.0

specification/documentation/CreateMessage.md, specification/documentation/CreateMessageBatch.md, specification/responses/4xx/message_batches/400_UnableToProcessMessageBatch.yaml, specification/responses/4xx/message_batches/404_NoSuchRoutingPlanForBatch.yaml, specification/responses/4xx/messages/400_UnableToProcessMessage.yaml, specification/responses/4xx/messages/404_NoSuchRoutingPlanForMessage.yaml, specification/responses/5xx/message_batches/500_InternalServerErrorForBatch.yaml, specification/responses/5xx/messages/500_InternalServerErrorForMessage.yaml, specification/schemas/components/Recipient.yaml
Removed Date of Birth from the API docs.
=> CCM-7681: Remove DOB from API Docs

docs/tests/integration/post_v1_message-batches/happy_path.md, docs/tests/integration/post_v1_messages/happy_path.md, tests/integration/message_batches/create_message_batches/test_field_validation.py, tests/integration/message_batches/create_message_batches/test_success.py, tests/integration/messages/create_messages/test_success.py
=> CCM-8083: Hotfix for tests

docs/tests/integration/post_v1_message-batches/happy_path.md, docs/tests/integration/post_v1_messages/happy_path.md, tests/integration/message_batches/create_message_batches/test_field_validation.py, tests/integration/message_batches/create_message_batches/test_success.py, tests/integration/messages/create_messages/test_success.py
A hotfix release to fix integration tests.
=> Release Hotfix V4.32.1

docs/tests/integration/post_v1_message-batches/happy_path.md, docs/tests/integration/post_v1_messages/happy_path.md, tests/integration/message_batches/create_message_batches/test_field_validation.py, tests/integration/message_batches/create_message_batches/test_success.py, tests/integration/messages/create_messages/test_success.py
=> CCM-8083 bring hotfix into release

.github/workflows/continuous-integration.yml
Update CI job setup-python and increment patch version
=> CCM-8345: Update CI setup-python action

.github/workflows/continuous-integration.yml
=> CCM-8331: Release v4.34.1 merge to master

specification/documentation/APIDescription.md
Updated the NHS Notify API documentation to reflect the current process of onboarding
=> CCM-8355: Update API Documentation: Smoke Testing Section

tests/lib/helper.py
=> CCM-8471: APIM E2E Test fix

specification/responses/4xx/413_RequestEntityTooLarge.yaml, specification/responses/4xx/message_batches/422_DuplicateBatchRequest.yaml, specification/responses/4xx/messages/422_DuplicateMessageRequest.yaml
Changes for two tickets combined in this PR:
* [CCM-8371](https://nhsd-jira.digital.nhs.uk/browse/CCM-8371): Amend wording of 422 error responses
* [CCM-8470](https://nhsd-jira.digital.nhs.uk/browse/CCM-8470): Request too large docs are incomplete
=> CCM-8371 422 & 313 response code documenation

specification/documentation/APIDescription.md, specification/responses/4xx/413_RequestEntityTooLarge.yaml, specification/responses/4xx/message_batches/422_DuplicateBatchRequest.yaml, specification/responses/4xx/messages/422_DuplicateMessageRequest.yaml
=> CCM-8582: Release PR

README.md, example.env
- update readme testing section
- update sample .env file with required values
=> CCM-8638: Update README and sample .env file

azure/azure-release-pipeline.yml, tests/lib/authentication.py, tests/lib/fixtures.py
=> CCM-9223: Update release pipeline to pass in 'environment' variable

azure/azure-release-pipeline.yml, tests/lib/authentication.py, tests/lib/fixtures.py
Fixes:
- https://github.com/NHSDigital/communications-manager-api/pull/904
Following: https://nhsd-confluence.digital.nhs.uk/display/RIS/Patching+Steps. We are going to see what happens if we merge via UI. If the `+patch` commit is removed when merging to master then we'll add a commit to the head of master + release branches.
=> CCM-9210: Release v4.39.1

azure/azure-release-pipeline.yml
=> CCM-9223  fix typo

azure/azure-release-pipeline.yml
Fixes: 
- https://github.com/NHSDigital/communications-manager-api/pull/908
=> CCM-9210: Release v4.39.2

azure/azure-release-pipeline.yml
=> CCM-9223: Fix Release Pipeline

azure/azure-release-pipeline.yml
Fixes:
- https://github.com/NHSDigital/communications-manager-api/pull/915
=> CCM-9210: Release v4.39.3

specification/schemas/components/MessageStatus.yaml
=> CCM-9232: [API Docs] Change MinItems from 1 to 0 on `channels` array

azure/templates/run-tests.yml
=> CCM-9367: Fix nightly int/prod pipelines

azure/templates/run-tests.yml, proxies/shared/partials/Partial.Target.FaultRules.xml, proxies/shared/resources/jsc/EnhanceErrorDetails.js, sandbox/__test__/batch_send.spec.js, sandbox/__test__/messages.spec.js, sandbox/handlers/error_scenarios/override_contact_details.js, specification/documentation/APIDescription.md, specification/schemas/components/MessageStatus.yaml
=> CCM-9675: Release v4.40.0

tests/end_to_end/test_email.py, tests/end_to_end/test_letter.py, tests/end_to_end/test_nhsapp.py, tests/end_to_end/test_sms.py, tests/lib/helper.py
Include new form of authentication in apim e2e tests
=> CCM-9690: Fix apim e2e auth

sandbox/__test__/batch_send.spec.js, sandbox/__test__/messages.spec.js, sandbox/handlers/error_scenarios/override_contact_details.js
Updated the sandbox to include new scenarios for the PatientName override contact details feature. Also updated outdated unit tests to reflect current backend responses.
=> CCM-8894: Update sandbox to include patientName scenarios

README.md, example.env
Update Readme to add detail about authentication envar setup
=> CCM-9156: Update readme for envar setup

specification/documentation/APIDescription.md
=> CCM-10228: Release v4.43.0 merge to master

package.json, pnpm-lock.yaml
=> CCM-9871: Update Redoc to v2.5.0

specification/documentation/APIDescription.md
Update the "Onboarding" section of API documentation
=> CCM-11522: Update API Docs "Onboarding" section

README.md
Updated the `README.md` file to add details of using `asdf` to set up the necessary tools for development. Also applied various other formatting changes suggested by the [VSCode markdownlint plugin](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) and fixed the build badge at the top.
=> CCM-9688: README Updates
